package com.halfcooler.menu;

import com.halfcooler.flying.warplane.WarplaneHero;
import com.halfcooler.game.record.Record;
import com.halfcooler.game.record.Recorder;

import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.lang.reflect.Method;
import java.util.ResourceBundle;

public class DeadDialog extends JDialog
{
	private JPanel contentPane;
	private JButton buttonOK;
	private JButton buttonCancel;
	private JTextField textField1;
	private JLabel difficultyLabel;
	private JLabel timeLabel;
	private JLabel timeHS;
	private JLabel scoreLabel;
	private JLabel scoreHS;
	private JLabel damageLabel;
	private JLabel damageHS;
	private JLabel totalLabel;
	private JLabel totalHS;
	private JLabel enemyLabel;
	private JLabel enemyHS;
	private JLabel eliteLabel;
	private JLabel eliteHS;
	private JLabel plusLabel;
	private JLabel plusHS;
	private JLabel bossLabel;
	private JLabel bossHS;

	private final WarplaneHero heroo;

	public DeadDialog(WarplaneHero hero)
	{
		this.heroo = hero;
		$$$setupUI$$$();
		setContentPane(contentPane);
		setModal(true);
		getRootPane().setDefaultButton(buttonOK);

		buttonOK.addActionListener(_ -> onOK());

		buttonCancel.addActionListener(_ -> onCancel());

		// 点击 X 时调用 onCancel()
		setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
		addWindowListener(new WindowAdapter()
		{
			public void windowClosing(WindowEvent e)
			{
				onCancel();
			}
		});

		// 遇到 ESCAPE 时调用 onCancel()
		contentPane.registerKeyboardAction(_ -> onCancel(), KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);

		// 显示各项数据
		java.util.List<com.halfcooler.game.record.Record> records = Recorder.ReadRecords();

		// 难度
		this.difficultyLabel.setText(switch (hero.Difficulty)
		{
			case 0 -> this.$$$getMessageFromBundle$$$("language", "mode.easy");
			case 1 -> this.$$$getMessageFromBundle$$$("language", "mode.normal");
			case 2 -> this.$$$getMessageFromBundle$$$("language", "mode.hard");
			default -> throw new IllegalStateException("Unexpected value: " + hero.Difficulty);
		});

		String highScoreText = this.$$$getMessageFromBundle$$$("language", "record.high_score");
		// 时间
		this.timeLabel.setText(String.valueOf(hero.Time));
		this.timeHS.setText(hero.Time > records.stream().mapToInt(Record::time).max().orElse(0) ? highScoreText : "");

		// 分数
		this.scoreLabel.setText(String.valueOf(hero.Score));
		this.scoreHS.setText(hero.Score > records.stream().mapToInt(Record::score).max().orElse(0) ? highScoreText : "");

		// 伤害
		this.damageLabel.setText(String.valueOf(hero.DamagedTotal));
		this.damageHS.setText(hero.DamagedTotal < records.stream().mapToInt(Record::damage).max().orElse(0) ? this.$$$getMessageFromBundle$$$("language", "record.min_damage") : "");

		// 击杀总数
		int total = hero.Enemy + hero.Elite + hero.Plus + hero.Boss;
		this.totalLabel.setText(String.valueOf(total));
		this.totalHS.setText(total > records.stream().mapToInt(r -> r.enemy() + r.elite() + r.plus() + r.boss()).max().orElse(0) ? highScoreText : "");

		// 击杀普通
		this.enemyLabel.setText(String.valueOf(hero.Enemy));
		this.enemyHS.setText(hero.Enemy > records.stream().mapToInt(Record::enemy).max().orElse(0) ? highScoreText : "");

		// 击杀精英
		this.eliteLabel.setText(String.valueOf(hero.Elite));
		this.eliteHS.setText(hero.Elite > records.stream().mapToInt(Record::elite).max().orElse(0) ? highScoreText : "");

		// 击杀超级
		this.plusLabel.setText(String.valueOf(hero.Plus));
		this.plusHS.setText(hero.Plus > records.stream().mapToInt(Record::plus).max().orElse(0) ? highScoreText : "");

		// 击杀Boss
		this.bossLabel.setText(String.valueOf(hero.Boss));
		this.bossHS.setText(hero.Boss > records.stream().mapToInt(Record::boss).max().orElse(0) ? highScoreText : "");

	}

	private void onOK()
	{
		// 记录成绩
		String name = textField1.getText().trim();
		if (name.isEmpty())
			// 生成一个UUID
			name = "Anonymous";
		else if (name.length() > 32)
			name = name.substring(0, 32);
		Recorder.SaveRecords(new Record(name, heroo.Difficulty, heroo.Time, heroo.Score, heroo.DamagedTotal, heroo.Enemy, heroo.Elite, heroo.Plus, heroo.Boss));
		dispose();
	}

	private void onCancel()
	{
		// 必要时在此处添加您的代码
		dispose();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$()
	{
		contentPane = new JPanel();
		contentPane.setLayout(new GridBagLayout());
		final JPanel panel1 = new JPanel();
		panel1.setLayout(new GridBagLayout());
		GridBagConstraints gbc;
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 4;
		gbc.gridwidth = 4;
		gbc.weightx = 1.0;
		gbc.anchor = GridBagConstraints.EAST;
		contentPane.add(panel1, gbc);
		final JPanel panel2 = new JPanel();
		panel2.setLayout(new GridBagLayout());
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.weighty = 1.0;
		gbc.fill = GridBagConstraints.BOTH;
		panel1.add(panel2, gbc);
		buttonCancel = new JButton();
		buttonCancel.setText("Cancel");
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 0;
		gbc.weightx = 1.0;
		gbc.weighty = 1.0;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		panel2.add(buttonCancel, gbc);
		buttonOK = new JButton();
		buttonOK.setText("OK");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.weightx = 1.0;
		gbc.weighty = 1.0;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		panel2.add(buttonOK, gbc);
		final JLabel label1 = new JLabel();
		label1.setHorizontalTextPosition(0);
		this.$$$loadLabelText$$$(label1, this.$$$getMessageFromBundle$$$("language", "dead.name"));
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.gridwidth = 4;
		gbc.weighty = 1.0;
		contentPane.add(label1, gbc);
		final JLabel label2 = new JLabel();
		this.$$$loadLabelText$$$(label2, this.$$$getMessageFromBundle$$$("language", "dead.input_name"));
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 2;
		gbc.gridwidth = 3;
		gbc.gridheight = 2;
		gbc.weighty = 1.0;
		gbc.anchor = GridBagConstraints.WEST;
		contentPane.add(label2, gbc);
		textField1 = new JTextField();
		gbc = new GridBagConstraints();
		gbc.gridx = 3;
		gbc.gridy = 2;
		gbc.weightx = 1.0;
		gbc.weighty = 1.0;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		contentPane.add(textField1, gbc);
		final JPanel panel3 = new JPanel();
		panel3.setLayout(new GridBagLayout());
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 1;
		gbc.gridwidth = 4;
		gbc.fill = GridBagConstraints.BOTH;
		contentPane.add(panel3, gbc);
		difficultyLabel = new JLabel();
		difficultyLabel.setText("Label");
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 0;
		gbc.anchor = GridBagConstraints.WEST;
		panel3.add(difficultyLabel, gbc);
		final JLabel label3 = new JLabel();
		this.$$$loadLabelText$$$(label3, this.$$$getMessageFromBundle$$$("language", "record.difficulty"));
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.anchor = GridBagConstraints.WEST;
		panel3.add(label3, gbc);
		final JLabel label4 = new JLabel();
		this.$$$loadLabelText$$$(label4, this.$$$getMessageFromBundle$$$("language", "record.time"));
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 2;
		gbc.anchor = GridBagConstraints.WEST;
		panel3.add(label4, gbc);
		timeLabel = new JLabel();
		timeLabel.setText("Label");
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 2;
		gbc.anchor = GridBagConstraints.WEST;
		panel3.add(timeLabel, gbc);
		final JLabel label5 = new JLabel();
		this.$$$loadLabelText$$$(label5, this.$$$getMessageFromBundle$$$("language", "record.score"));
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 4;
		gbc.anchor = GridBagConstraints.WEST;
		panel3.add(label5, gbc);
		scoreLabel = new JLabel();
		scoreLabel.setText("Label");
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 4;
		gbc.anchor = GridBagConstraints.WEST;
		panel3.add(scoreLabel, gbc);
		final JLabel label6 = new JLabel();
		this.$$$loadLabelText$$$(label6, this.$$$getMessageFromBundle$$$("language", "record.damage"));
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 6;
		gbc.anchor = GridBagConstraints.WEST;
		panel3.add(label6, gbc);
		damageLabel = new JLabel();
		damageLabel.setText("Label");
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 6;
		gbc.anchor = GridBagConstraints.WEST;
		panel3.add(damageLabel, gbc);
		final JLabel label7 = new JLabel();
		this.$$$loadLabelText$$$(label7, this.$$$getMessageFromBundle$$$("language", "record.killed.total"));
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 8;
		gbc.anchor = GridBagConstraints.WEST;
		panel3.add(label7, gbc);
		totalLabel = new JLabel();
		totalLabel.setText("Label");
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 8;
		gbc.anchor = GridBagConstraints.WEST;
		panel3.add(totalLabel, gbc);
		final JLabel label8 = new JLabel();
		this.$$$loadLabelText$$$(label8, this.$$$getMessageFromBundle$$$("language", "record.killed.enemy"));
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 10;
		gbc.anchor = GridBagConstraints.WEST;
		panel3.add(label8, gbc);
		enemyLabel = new JLabel();
		enemyLabel.setText("Label");
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 10;
		gbc.anchor = GridBagConstraints.WEST;
		panel3.add(enemyLabel, gbc);
		final JLabel label9 = new JLabel();
		this.$$$loadLabelText$$$(label9, this.$$$getMessageFromBundle$$$("language", "record.killed.elite"));
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 11;
		gbc.anchor = GridBagConstraints.WEST;
		panel3.add(label9, gbc);
		eliteLabel = new JLabel();
		eliteLabel.setText("Label");
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 11;
		gbc.anchor = GridBagConstraints.WEST;
		panel3.add(eliteLabel, gbc);
		final JLabel label10 = new JLabel();
		this.$$$loadLabelText$$$(label10, this.$$$getMessageFromBundle$$$("language", "record.killed.plus"));
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 12;
		gbc.anchor = GridBagConstraints.WEST;
		panel3.add(label10, gbc);
		plusLabel = new JLabel();
		plusLabel.setText("Label");
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 12;
		gbc.anchor = GridBagConstraints.WEST;
		panel3.add(plusLabel, gbc);
		scoreHS = new JLabel();
		scoreHS.setText("Label");
		gbc = new GridBagConstraints();
		gbc.gridx = 3;
		gbc.gridy = 4;
		gbc.anchor = GridBagConstraints.WEST;
		panel3.add(scoreHS, gbc);
		timeHS = new JLabel();
		timeHS.setText("Label");
		gbc = new GridBagConstraints();
		gbc.gridx = 3;
		gbc.gridy = 2;
		gbc.anchor = GridBagConstraints.WEST;
		panel3.add(timeHS, gbc);
		damageHS = new JLabel();
		damageHS.setText("Label");
		gbc = new GridBagConstraints();
		gbc.gridx = 3;
		gbc.gridy = 6;
		gbc.anchor = GridBagConstraints.WEST;
		panel3.add(damageHS, gbc);
		totalHS = new JLabel();
		totalHS.setText("Label");
		gbc = new GridBagConstraints();
		gbc.gridx = 3;
		gbc.gridy = 8;
		gbc.anchor = GridBagConstraints.WEST;
		panel3.add(totalHS, gbc);
		enemyHS = new JLabel();
		enemyHS.setText("Label");
		gbc = new GridBagConstraints();
		gbc.gridx = 3;
		gbc.gridy = 10;
		gbc.anchor = GridBagConstraints.WEST;
		panel3.add(enemyHS, gbc);
		eliteHS = new JLabel();
		eliteHS.setText("Label");
		gbc = new GridBagConstraints();
		gbc.gridx = 3;
		gbc.gridy = 11;
		gbc.anchor = GridBagConstraints.WEST;
		panel3.add(eliteHS, gbc);
		plusHS = new JLabel();
		plusHS.setText("Label");
		gbc = new GridBagConstraints();
		gbc.gridx = 3;
		gbc.gridy = 12;
		gbc.anchor = GridBagConstraints.WEST;
		panel3.add(plusHS, gbc);
		final JLabel label11 = new JLabel();
		this.$$$loadLabelText$$$(label11, this.$$$getMessageFromBundle$$$("language", "record.killed.boss"));
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 13;
		gbc.anchor = GridBagConstraints.WEST;
		panel3.add(label11, gbc);
		bossLabel = new JLabel();
		bossLabel.setText("Label");
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 13;
		gbc.anchor = GridBagConstraints.WEST;
		panel3.add(bossLabel, gbc);
		bossHS = new JLabel();
		bossHS.setText("Label");
		gbc = new GridBagConstraints();
		gbc.gridx = 3;
		gbc.gridy = 13;
		gbc.anchor = GridBagConstraints.WEST;
		panel3.add(bossHS, gbc);
		final JPanel spacer1 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 1;
		gbc.gridwidth = 4;
		gbc.fill = GridBagConstraints.VERTICAL;
		panel3.add(spacer1, gbc);
		final JPanel spacer2 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 3;
		gbc.gridwidth = 4;
		gbc.fill = GridBagConstraints.VERTICAL;
		panel3.add(spacer2, gbc);
		final JPanel spacer3 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 5;
		gbc.gridwidth = 4;
		gbc.fill = GridBagConstraints.VERTICAL;
		panel3.add(spacer3, gbc);
		final JPanel spacer4 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 7;
		gbc.gridwidth = 4;
		gbc.fill = GridBagConstraints.VERTICAL;
		panel3.add(spacer4, gbc);
		final JPanel spacer5 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 9;
		gbc.gridwidth = 4;
		gbc.fill = GridBagConstraints.VERTICAL;
		panel3.add(spacer5, gbc);
		final JPanel spacer6 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 14;
		gbc.gridwidth = 4;
		gbc.fill = GridBagConstraints.VERTICAL;
		panel3.add(spacer6, gbc);
		final JPanel spacer7 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 2;
		gbc.gridy = 0;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		panel3.add(spacer7, gbc);
	}

	private static Method $$$cachedGetBundleMethod$$$ = null;

	private String $$$getMessageFromBundle$$$(String path, String key)
	{
		ResourceBundle bundle;
		try
		{
			Class<?> thisClass = this.getClass();
			if ($$$cachedGetBundleMethod$$$ == null)
			{
				Class<?> dynamicBundleClass = thisClass.getClassLoader().loadClass("com.intellij.DynamicBundle");
				$$$cachedGetBundleMethod$$$ = dynamicBundleClass.getMethod("getBundle", String.class, Class.class);
			}
			bundle = (ResourceBundle) $$$cachedGetBundleMethod$$$.invoke(null, path, thisClass);
		} catch (Exception e)
		{
			bundle = ResourceBundle.getBundle(path);
		}
		return bundle.getString(key);
	}

	/**
	 * @noinspection ALL
	 */
	private void $$$loadLabelText$$$(JLabel component, String text)
	{
		StringBuffer result = new StringBuffer();
		boolean haveMnemonic = false;
		char mnemonic = '\0';
		int mnemonicIndex = -1;
		for (int i = 0; i < text.length(); i++)
		{
			if (text.charAt(i) == '&')
			{
				i++;
				if (i == text.length()) break;
				if (!haveMnemonic && text.charAt(i) != '&')
				{
					haveMnemonic = true;
					mnemonic = text.charAt(i);
					mnemonicIndex = result.length();
				}
			}
			result.append(text.charAt(i));
		}
		component.setText(result.toString());
		if (haveMnemonic)
		{
			component.setDisplayedMnemonic(mnemonic);
			component.setDisplayedMnemonicIndex(mnemonicIndex);
		}
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$()
	{
		return contentPane;
	}

}
