package com.halfcooler.menu;

import com.halfcooler.game.record.Recorder;
import com.halfcooler.utils.ResourcesBundler;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.ArrayList;

public class HallOfFameMenu extends JFrame
{

	private JTable table1;
	private JButton backButton;
	private JButton exitButton;
	private JScrollPane scrollPane1;

	private final ResourcesBundler rb = new ResourcesBundler();

	public HallOfFameMenu()
	{
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$()
	{
		createUIComponents();
		final JPanel panel1 = new JPanel();
		panel1.setLayout(new GridBagLayout());
		final JPanel panel2 = new JPanel();
		panel2.setLayout(new GridBagLayout());
		GridBagConstraints gbc;
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 1;
		gbc.fill = GridBagConstraints.BOTH;
		panel1.add(panel2, gbc);
		backButton = new JButton();
		backButton.setText("Back");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		panel2.add(backButton, gbc);
		exitButton = new JButton();
		exitButton.setText("Exit");
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 0;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		panel2.add(exitButton, gbc);
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.weightx = 1.0;
		gbc.weighty = 1.0;
		gbc.fill = GridBagConstraints.BOTH;
		panel1.add(scrollPane1, gbc);
		scrollPane1.setViewportView(table1);
	}

	private void createUIComponents()
	{
		String[] columnNames =
		{
			"UUID",
			rb.GetMessage("record.name"),
			rb.GetMessage("record.difficulty"),
			rb.GetMessage("record.score"),
			rb.GetMessage("record.damage"),
			rb.GetMessage("record.killed.total"),
			rb.GetMessage("record.killed.enemy"),
			rb.GetMessage("record.killed.elite"),
			rb.GetMessage("record.killed.plus"),
			rb.GetMessage("record.killed.boss")
		};

		java.util.List<String[]> data = new ArrayList<>();
		for (var record : Recorder.ReadBinaryRecord())
			data.add(record.Display());

		String[][] dataArray = new String[data.size()][];
		for (int i = 0; i < data.size(); i++)
			dataArray[i] = data.get(i);

		table1 = new JTable(dataArray, columnNames);
		table1.setModel(new DefaultTableModel()
		{
			@Override
			public boolean isCellEditable(int row, int column)
			{
				return false;
			}
		});

		// TODO: 啥必 table 不给我显示
		table1.setFillsViewportHeight(true);
		scrollPane1 = new JScrollPane(table1);
	}
}
