package com.halfcooler.menu;

import com.halfcooler.Program;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;

// Debug Pass
public class StartsMenu extends JFrame
{
	private JPanel panel;
	private JButton difficultyEasyButton;
	private JButton difficultyNormalButton;
	private JButton difficultyHardButton;
	private JCheckBox musicCheckBox;

	private int difficulty = 0;
	private boolean musicOn = false;

	public StartsMenu()
	{

		$$$setupUI$$$();

		this.difficultyEasyButton.addActionListener( (ActionEvent ignored) ->
		{
			this.difficulty = 0;
			this.onButtonClicked();
		});

		this.difficultyNormalButton.addActionListener( (ActionEvent ignored) ->
		{
			this.difficulty = 1;
			this.onButtonClicked();
		});

		this.difficultyHardButton.addActionListener( (ActionEvent ignored) ->
		{
			this.difficulty = 2;
			this.onButtonClicked();
		});
	}

	public JPanel GetPanel()
	{
		return this.panel;
	}

	public int GetDifficulty()
	{
		return this.difficulty;
	}

	public boolean IsMusicOn()
	{
		return this.musicOn;
	}

	private void onButtonClicked()
	{
		this.panel.setVisible(false);
		this.musicOn = musicCheckBox.isSelected();

		synchronized (Program.MainLock)
		{
			Program.MainLock.notify();
		}
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$()
	{
		panel = new JPanel();
		panel.setLayout(new GridBagLayout());
		difficultyEasyButton = new JButton();
		difficultyEasyButton.setText("Easy Mode");
		GridBagConstraints gbc;
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.weightx = 1.0;
		gbc.weighty = 1.0;
		panel.add(difficultyEasyButton, gbc);
		difficultyNormalButton = new JButton();
		difficultyNormalButton.setText("Normal Mode");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 1;
		gbc.weightx = 1.0;
		gbc.weighty = 1.0;
		panel.add(difficultyNormalButton, gbc);
		musicCheckBox = new JCheckBox();
		musicCheckBox.setText("Music On");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 3;
		gbc.weightx = 1.0;
		gbc.weighty = 1.0;
		panel.add(musicCheckBox, gbc);
		difficultyHardButton = new JButton();
		difficultyHardButton.setText("Hard Mode");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 2;
		gbc.weightx = 1.0;
		gbc.weighty = 1.0;
		panel.add(difficultyHardButton, gbc);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$()
	{
		return panel;
	}

}
